CUDA_VISIBLE_DEVICES=2 python train.py \
    --model_name 'no_contrast' \
    --train_img_path '/home/wenliang/6691-project/data/train_img' \
    --train_mask_path '/home/wenliang/6691-project/data/train_mask' \
    --valid_img_path '/home/wenliang/6691-project/data/valid_img' \
    --valid_mask_path '/home/wenliang/6691-project/data/valid_mask' \
    --description_path '/home/wenliang/6691-project/gen_prompt/gpt3.5_output.json' \
    --img_size 224 \
    --num_classes 2 \
    --epochs 150 \
    --base_lr 0.001 \
    --batch_size 64 \
    --embed_dim 96 \
    --depths_encoder 1 1 1 1 \
    --depths_decoder 1 1 1 1\
    --num_heads 8 8 8 8\